#!/bin/bash

HOST=192.168.88.7

if ping -c 3 ${HOST} | grep -e "mdev" >/dev/null; then
    echo "[***] Резервне копіювання 00_setup..."
    rsync -a --delete --quiet -e "ssh -p 2241 -i /home/roman/.ssh/id_serv" /home/roman/00_setup serv@192.168.88.7:/run/media/serv/media

    echo "[***] Резервне копіювання 01_project..."
    rsync -a --delete --quiet -e "ssh -p 2241 -i /home/roman/.ssh/id_serv" /home/roman/01_project serv@192.168.88.7:/run/media/serv/media

    echo "[***] Резервне копіювання 03_work..."
    rsync -a --delete --quiet -e "ssh -p 2241 -i /home/roman/.ssh/id_serv" /home/roman/03_work serv@192.168.88.7:/run/media/serv/media

    echo "[***] Резервне копіювання Documents..."
    rsync -a --delete --quiet -e "ssh -p 2241 -i /home/roman/.ssh/id_serv" /home/roman/Documents serv@192.168.88.7:/run/media/serv/media

    echo "[***] Резервне копіювання Music..."
    rsync -a --delete --quiet -e "ssh -p 2241 -i /home/roman/.ssh/id_serv" /home/roman/Music serv@192.168.88.7:/run/media/serv/media

    echo "[***] Резервне копіювання Pictures..."
    rsync -a --delete --quiet -e "ssh -p 2241 -i /home/roman/.ssh/id_serv" /home/roman/Pictures serv@192.168.88.7:/run/media/serv/media

    echo "[***] Резервне копіювання Videos..."
    rsync -a --delete --quiet -e "ssh -p 2241 -i /home/roman/.ssh/id_serv" /home/roman/Videos serv@192.168.88.7:/run/media/serv/media
else
    echo "ERROR !!!!!"
fi

echo "[***] END..."
