#!/bin/bash

color() {
	case "$1" in
	red)
		echo -e "\n\033[31m$2\033[0m"
		;;
	yellow)
		echo -e "\n\033[33m$2\033[0m"
		;;
	green)
		echo -e "\n\033[32m$2\033[0m"
		;;
	esac
}

color green "[***] Резервне копіювання на ПК > HOME ..."
rsync -a --delete --quiet -e "ssh -p 2241" serv@192.168.88.7:/run/media/serv/media/ ~/

# color green "[***] Резервне копіювання 00_setup..."
# rsync -a --delete --quiet -e "ssh -p 2241" serv@192.168.88.7:/run/media/serv/media/00_setup ~/
#
# color green "[***] Резервне копіювання 01_project..."
# rsync -a --delete --quiet -e "ssh -p 2241" serv@192.168.88.7:/run/media/serv/media/01_project ~/
#
# color green "[***] Резервне копіювання 02_work..."
# rsync -a --delete --quiet -e "ssh -p 2241" serv@192.168.88.7:/run/media/serv/media/02_work ~/
#
# color green "[***] Резервне копіювання Documents..."
# rsync -a --delete --quiet -e "ssh -p 2241" serv@192.168.88.7:/run/media/serv/media/Documents ~/
#
# color green "[***] Резервне копіювання Music..."
# rsync -a --delete --quiet -e "ssh -p 2241" serv@192.168.88.7:/run/media/serv/media/Music ~/
#
# color green "[***] Резервне копіювання Pictures..."
# rsync -a --delete --quiet -e "ssh -p 2241" serv@192.168.88.7:/run/media/serv/media/Pictures ~/
#
# color green "[***] Резервне копіювання Videos..."
# rsync -a --delete --quiet -e "ssh -p 2241" serv@192.168.88.7:/run/media/serv/media/Videos ~/

color yellow "[***] END..."
