# Рядок праворуч
right_format = """
$time\
$battery\
"""

# Заміняти символ '❯' в командному рядку на символ  '➜'
[character] # Назва модуля, який ми налаштовуємо – 'character'
success_symbol = '[➜](bold green)' # Частина 'success_symbol' буде використовувати символ '➜' підсвічений значенням 'bold green'
error_symbol = '[✗](bold red)'


[directory]
truncation_length = 8
truncation_symbol = '…/'
read_only = ' 🔒'
truncate_to_repo = false

# [time]
# disabled = false
# format = '🕙[ $time ]($style) '
# time_format = '%T'
# # utc_time_offset = '-5'
#
# [[battery.display]]
# threshold = 100
# style = 'green'
#
# [[battery.display]]
# threshold = 60
# style = 'yellow'
#
# [[battery.display]]
# threshold = 30
# style = 'bold red'
#
# [battery]
# full_symbol = '󰁹 '
# charging_symbol = '󰂄 '
# discharging_symbol = '󰂃 '
# unknown_symbol = '󰁽 '
# empty_symbol = '󰂎 '
